#!/bin/bash
KLIPPER_REPO="https://github.com/KevinOConnor/klipper"

pushd $HOME
git clone --depth 1 $KLIPPER_REPO klipper
pushd klipper
sed -i 's/pip -r/pip --no-cache-dir -r /g' ./klipper/scripts/install-debian.sh
chmod u+x ./klipper/scripts/install-debian.sh && ./klipper/scripts/install-debian.sh
sudo systemctl disable klipper.service
popd
